// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOgcFemi1kcICIr0fj2FWRQfnN3L547LA',
    appId: '1:327673877174:web:e8bfa875cfe8a68d258c17',
    messagingSenderId: '327673877174',
    projectId: 'my-project-729f2',
    authDomain: 'my-project-729f2.firebaseapp.com',
    storageBucket: 'my-project-729f2.firebasestorage.app',
    measurementId: 'G-BDL30EXNQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-7L1bynxXr796yp4KnL-gT9LRvxH4d5U',
    appId: '1:327673877174:android:dbb2b9f552dda3aa258c17',
    messagingSenderId: '327673877174',
    projectId: 'my-project-729f2',
    storageBucket: 'my-project-729f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv4ztMX5jAyZbqEa2PV59Nem5wPfsk5FM',
    appId: '1:327673877174:ios:704752dbf52c9b09258c17',
    messagingSenderId: '327673877174',
    projectId: 'my-project-729f2',
    storageBucket: 'my-project-729f2.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv4ztMX5jAyZbqEa2PV59Nem5wPfsk5FM',
    appId: '1:327673877174:ios:704752dbf52c9b09258c17',
    messagingSenderId: '327673877174',
    projectId: 'my-project-729f2',
    storageBucket: 'my-project-729f2.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOgcFemi1kcICIr0fj2FWRQfnN3L547LA',
    appId: '1:327673877174:web:8dbca34bbf5fec21258c17',
    messagingSenderId: '327673877174',
    projectId: 'my-project-729f2',
    authDomain: 'my-project-729f2.firebaseapp.com',
    storageBucket: 'my-project-729f2.firebasestorage.app',
    measurementId: 'G-WZF99SP32V',
  );
}
